### ISSUE TITLE
Not installing on Alfred v3.2.1[768]/macOS Sierra

### ISSUE THREAD

**Issue by verwinv** [wesbos/Cobalt2-Alfred-Theme#3]
Hi Wes,

Much thanks for the lovely theme - happy user for a while now.

Trying to install it on a new machine with Sierra, it somehow won't open in Alfred.

Any idea what could be going wrong?

Kind regards, Erwin

**Comment by wesbos** [comment]
Hey! Are you on Alfred 3? I haven't upgraded, maybe that is why?

**Comment by verwinv** [comment]
Version 3 it is! I was on 3 on my other machine as well - though on El Capitan, not Sierra like I am on this one (where the non-installing happens). Should I take it up with Alfred service desk and report back on what they say?

**Comment by ngdot** [comment]
@verwinv have you got a powerpack? You need it to import a theme.
> Powerpack users can also create or import custom themes, allowing you to match Alfred to your desktop or to your mood!

**Comment by verwinv** [comment]
@NicolasGoerlach yes, I do! Other V3 themes import just fine. Version 3 introduced a "new intuitive theme editor" which probably introduced some changes in how the theming functions.

**Comment by ngdot** [comment]
Hm thats strange, got the same version on sierra too, and all works fine.. Maybe u should clean the Application Cache under "Advanced" and try it again.

**Comment by verwinv** [comment]
@NicolasGoerlach That totally did the trick! Thanks much!
